---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: cida-centos-6.6-vbox
    driver:
      box: usgs-wsi-centos-6.6-vbox
      box_url: ftp://ftpext.usgs.gov/pub/er/wi/middleton/dblodgett/boxes/virtualbox/opscode_centos-6.6_chef-provisionerless.box
  - name: cida-centos-6.6-vmware
    driver:
      box: usgs-wsi-centos-6.6-vmware
      box_url: ftp://ftpext.usgs.gov/pub/er/wi/middleton/dblodgett/boxes/vmware/opscode_centos-6.6_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[cida_jenkins::default]
    attributes:
  - name: full_stack
    driver:
      network:
      - ["private_network", {ip: "10.0.0.10"}]
    run_list:
      - recipe[stig::default]
      - recipe[auditd::rules]
      - recipe[jenkins::java]
      - recipe[jenkins::master]
      - recipe[cida_jenkins::default]
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    attributes:
      auditd:
        ruleset: "cis"